trigger:
  branches:
    include:
      - dev
  paths:
    include:
      - k8s/aks/azuredeploy.json
stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job:  Build
        displayName:  build job
        pool:
          name: "Azure Pipelines"
          vmImage: "vs2017-win2016"
        steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: |
              # Write your PowerShell commands here.
              Write-Host "Validating ARM Template"
        - task: AzSKARMTemplateChecker@4
          inputs:
            ARMTemplateFilePath: 'k8s/aks/azuredeploy.json'
  - stage: Deploy
    displayName: Deploy AKS infra
    jobs:
      - job: Deploy
        displayName: Deploy AKS infra
        pool:
          name: "Azure Pipelines"
          vmImage: "vs2017-win2016"
        steps: 
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            ConnectedServiceName: 'EMC-Azure'
            subscriptionName: '9c326498-2371-4955-8465-8a7f665db362'
            action: 'Create Or Update Resource Group'
            resourceGroupName: 'aks-demo'
            location: 'South Central US'
            templateLocation: 'Linked artifact'
            csmFile: 'k8s/aks/azuredeploy.json'
            overrideParameters: '-AKSClusterName $(ClusterName)'
            deploymentMode: 'Incremental'
        