trigger:
  branches:
    include:
      - dev
  paths:
    include:
      - k8s/aks/azuredeploy.json
stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job:  Build
        displayName:  build job
        pool:
          name: "Azure Pipelines"
          vmImage: "vs2017-win2016"
        steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: |
              # Write your PowerShell commands here.
              Write-Host "Validating ARM Template"
  - stage: Deploy
    displayName: Deploy AKS infra
    jobs:
      - job: Deploy
        displayName: Deploy AKS infra
        pool:
          name: "Azure Pipelines"
          vmImage: "vs2017-win2016"
        steps:
          - 
        