trigger:
- dev
stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job:  Build
        displayName:  build job
        pool:
          name: "Azure Pipelines"
          vmImage: "vs2017-win2016"
        steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: |
              # Write your PowerShell commands here.
              Write-Host "Hello World"